### PR TITLE
[WIP] Launcher

### PR DESCRIPTION
**Pull request by TimAdamek**
launcherscreenshot1

The launcher to install modules.

### CODE REVIEW

**Comment by boeserwolf91** [comment]
Can you remove the files from the .idea directory please? (Change the .gitignore so that every .idea directory is meant and not just the folder from the root dir)

**Comment by boeserwolf91** [comment]
forget the parenthesized words. you added it as a module to the root pom. therefore just removing the .idea folder from the launcher directory should be enough.

**Comment by pschichtel** [comment]
Given that the module names tend to be short, a multi-column list might be useful.

Preferrably counting sideways to keep the columns balanced:
```
1 2 3
4 5 6
7 8
```

**Comment by pschichtel** [comment]
new screenshots ?

**Comment by pschichtel** [comment]
Closing this due to inactivity and being obsoleted by the [JarMerger](https://github.com/CubeEngine/JarMerger) web application.

**Pull request closed without merging**
